version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: pipeline_kafka_zookeeper
    network_mode: host
    ports:
      - "2181:2181"
  kafka0:
    image: wurstmeister/kafka:0.8.2.2
    container_name: pipeline_kafka_broker0
    network_mode: host
    environment:
      KAFKA_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka1:
    extends:
      service: kafka0
    container_name: pipeline_kafka_broker1
    ports:
      - "8092:9092"
    environment:
      KAFKA_PORT: 8092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 8092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
